# Generated by Django 5.1.4 on 2025-01-04 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0001_initial'),
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_size', models.CharField(max_length=50)),
                ('product_makingprice', models.CharField(max_length=50)),
                ('product_weight', models.CharField(max_length=50)),
                ('product_photo', models.FileField(upload_to='Assets/Shop/')),
                ('product_details', models.CharField(max_length=100)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_shop')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_type')),
            ],
        ),
    ]
