# Generated by Django 5.1.4 on 2025-01-04 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_product',
        ),
    ]
