# Generated by Django 5.1.4 on 2025-01-04 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=30)),
                ('shop_email', models.CharField(max_length=30)),
                ('shop_contact', models.CharField(max_length=30)),
                ('shop_proof', models.FileField(upload_to='Assets/UserDocs/')),
                ('shop_photo', models.FileField(upload_to='Assets/UserDocs/')),
                ('shop_status', models.CharField(max_length=30)),
                ('shop_address', models.CharField(max_length=30)),
                ('shop_password', models.CharField(max_length=30)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('user_email', models.CharField(max_length=30)),
                ('user_address', models.CharField(max_length=30)),
                ('user_contact', models.CharField(max_length=30)),
                ('user_gender', models.CharField(max_length=30)),
                ('user_password', models.CharField(max_length=30)),
                ('user_dob', models.DateField()),
                ('user_photo', models.FileField(upload_to='Assets/UserDocs/')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
