# Generated by Django 5.1.4 on 2025-01-06 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_tbl_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_customization',
            old_name='type',
            new_name='type_id',
        ),
    ]
