# Generated by Django 5.1.4 on 2025-01-06 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_rename_type_tbl_customization_type_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_customization',
        ),
    ]
