# Generated by Django 5.1.4 on 2025-01-06 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
        ('Guest', '0001_initial'),
        ('User', '0008_delete_tbl_customization'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_customization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customization_details', models.CharField(max_length=30)),
                ('customization_status', models.CharField(max_length=30)),
                ('customization_date', models.CharField(max_length=30)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_category')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_shop')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
