# Generated by Django 5.1.4 on 2025-01-06 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_tbl_customization'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_customization',
        ),
    ]
