# Generated by Django 5.1.4 on 2025-01-06 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_tbl_customization'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_customization',
        ),
    ]
