# Generated by Django 5.1.4 on 2025-01-08 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0019_tbl_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_customization',
        ),
    ]
