# Generated by Django 5.1.4 on 2025-01-08 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
        ('Guest', '0001_initial'),
        ('User', '0020_delete_tbl_customization'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_customization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customization_details', models.CharField(max_length=30)),
                ('customization_weight', models.CharField(max_length=30)),
                ('customization_status', models.IntegerField(default=0)),
                ('customization_date', models.DateField(auto_now_add=True)),
                ('customization_amount', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_category')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_shop')),
                ('types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
