# Generated by Django 5.1.4 on 2025-01-09 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0021_tbl_customization'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
    ]
