# Generated by Django 5.1.4 on 2025-01-09 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0023_tbl_complaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
    ]
